# Generated by Django 5.1.4 on 2026-04-28 17:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodne_cislo', models.CharField(blank=True, max_length=32, verbose_name='Rodné číslo / VS')),
                ('name', models.CharField(max_length=255, verbose_name='Jméno')),
                ('birth_year', models.CharField(blank=True, max_length=16, verbose_name='Rok narození')),
                ('school_class', models.CharField(blank=True, max_length=64, verbose_name='Třída')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Kontakt')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='Poznámka')),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrátor'), ('teacher', 'Učitel/ka'), ('asis', 'Asistent/ka')], default='teacher', max_length=16)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Kód třídy')),
                ('subject', models.CharField(max_length=128, verbose_name='Předmět')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='Počet hodin')),
                ('minutes_per_lesson', models.PositiveIntegerField(default=60, verbose_name='Délka hodiny (min)')),
                ('fee_per_lesson', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za hodinu (Kč)')),
                ('date_start', models.DateField(verbose_name='Datum začátku')),
                ('date_end', models.DateField(verbose_name='Datum konce')),
                ('status', models.CharField(choices=[('active', 'Aktivní'), ('close', 'Uzavřená')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_assisted', to=settings.AUTH_USER_MODEL, verbose_name='Asistent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes_taught', to=settings.AUTH_USER_MODEL, verbose_name='Učitel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Monday', 'Pondělí'), ('Tuesday', 'Úterý'), ('Wednesday', 'Středa'), ('Thursday', 'Čtvrtek'), ('Friday', 'Pátek'), ('Saturday', 'Sobota'), ('Sunday', 'Neděle')], max_length=10)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='core.classroom')),
            ],
            options={
                'ordering': ['weekday', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='core.classroom')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('classroom', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_lessons', models.PositiveIntegerField(default=0, verbose_name='Skutečný počet hodin')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
