# Generated by Django 6.0.1 on 2026-04-28 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_assisted', to=settings.AUTH_USER_MODEL, verbose_name='Assistant'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=64, verbose_name='Class code'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date_end',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date_start',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='fee_per_lesson',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price per lesson (CZK)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='minutes_per_lesson',
            field=models.PositiveIntegerField(default=60, verbose_name='Lesson length (min)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('close', 'Closed')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject',
            field=models.CharField(max_length=128, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes_taught', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of lessons'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='actual_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Actual lessons'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='note',
            field=models.CharField(blank=True, max_length=512, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_year',
            field=models.CharField(blank=True, max_length=16, verbose_name='Birth year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.CharField(blank=True, max_length=512, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rodne_cislo',
            field=models.CharField(blank=True, max_length=32, verbose_name='Birth number / VS'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.CharField(blank=True, max_length=64, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('asis', 'Assistant')], default='teacher', max_length=16),
        ),
    ]
